spring:
  application:
    name:
      PulseRoom
  output:
    ansi:
      enabled:
        always
## DATABASE , REDIS , SECURITY
  config:
    import :
      - "database.yaml"
      - "redis.yaml"
      - "security.yaml"
## JPA
  jpa:
    database:
      postgresql
    show-sql:
      true
    hibernate:
      ddl-auto:
        update
    properties:
      hibernate:
        format_sql:
          true
